easy_admin:
      site_name: '<em style="font-size: 100%;">Clothing </em> <em style="font-size: 80%;">store</em>'
      design:
              brand_color: '#81b9ba'

  #  site_name: '<img src=" https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQtzwmmUCoC5Jhuq9FgvlCT_u7IJsUlviBrC4HebS6uR1_Vedzx&usqp=CAU/50*50" />'
 

