easy_admin:
  design:
        brand_color: '#3498db'
        menu:
            - label: 'Store'
              icon: 'store'
              css_class: 'btn  btn-primary font-weight-bold text-white '
              children:
                  - {entity: 'Product', icon: 'tshirt', label: 'Products',css_class: 'font-weight-bold'}
                  - {entity: 'Category', icon: 'inbox', label: 'Categories',css_class: ' font-weight-bold '}