easy_admin:
    entities:

            User:
                class: App\Entity\User
                list:
                  max_results: 6
                  title: " List of %%entity_label%%"
                  actions:
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-info'}
                    - {name: 'delete', icon: 'trash-alt', label: false, css_class: 'btn btn-danger' }
                  
                  fields:
                   - {property: 'username'}
                   - {property: 'email'}
                   - {property: 'password'}
